// aprendiendo-vue/src/components/Blog.vue
<template>
  <div class="general">
    <slider texto="Blog" />
    <div class="center">
      <section id="content">
        <h2 class="subheader">Ultimos articulos</h2>
        <div id="articles" v-if="articles">
          <Article
            class="article-item"
            id="article-template"
            v-for="(article) of articles"
            :article="article"
            :key="article._id"
          />
          <!-- Añadir articulos via js -->
        </div>
      </section>
      <sidebar />
    </div>
  </div>
</template>
<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";
import axios from "axios";
import Global from "../Global";
import Article from "./Article";

export default {
  name: "Blog",
  components: {
    Slider,
    Sidebar,
    Article
  },
  data() {
    return {
      articles: [],
      url: Global.url
    };
  },
  methods: {
    getArticles() {
      axios.get(this.url + "articles").then(res => {
        if (res.data.status == "success") this.articles = res.data.articles;
        console.log(this.articles);
      });
    }
  },
  mounted() {
    this.getArticles();
  }
};
</script>

// aprendiendo-angular/src/app/components/blog/blog.component.ts
import { Component, OnInit } from '@angular/core';
import { ArticleService } from 'src/app/services/article.service';
import { Article } from 'src/app/models/article';
import { global } from '../../services/global';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.component.html',
  styleUrls: ['./blog.component.css'],
  providers: [ArticleService]
})
export class BlogComponent implements OnInit {

  public articles: Article[];
  public url: string;

  constructor(
    private _articleService: ArticleService
  ) {
    this.url = global.url;
  }

  ngOnInit() {
    console.log(this._articleService.pruebas());
    this._articleService.getArticles().subscribe(
      response => {
        if (response.articles) {
          this.articles = response.articles;
        }
      },
      error => {
        console.log(error);
      }
    );
  }

}

<app-slider [nombre]="'Blog'" [size]="'small'">
</app-slider>
<div class="center">
    <section id="content">
        <h1 class="subheader">Blog</h1>
        <div id="articles">
            <article class="article-item" id="article-template" *ngFor="let article of articles">
                <div class="image-wrap">
                    <img src="{{url + 'get-image/'+article.image}}" alt="{{article.title}}" *ngIf="article.image">
                    <img src="../../../assets/images/default.png" alt="{{article.title}}" *ngIf="!article.image">
                </div>

                <h2>{{article.title}}</h2>
                <span class="date">
                    {{article.date}}
                </span>
                <a href="#">Leer mas</a>
                <div class="clearfix"></div>
            </article>
            <!-- Añadir articulos via js -->
        </div>
    </section>
    <app-sidebar></app-sidebar>
</div>
