// aprendiendo-react/src/componets/Formulario.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Formulario extends Component {

    nombreRef = React.createRef();
    apellidoRef = React.createRef();
    biografiaRef = React.createRef();
    generoHombreRef = React.createRef();
    generoMujerRef = React.createRef();
    generoOtroRef = React.createRef();
    state = {
        user: {}
    }
    recibirFormulario = (e) => {
        e.preventDefault();

        var user = {
            nombre: this.nombreRef.current.value,
            apellido: this.apellidoRef.current.value,
            biografia: this.biografiaRef.current.value,
            genero: ((this.generoHombreRef.current.checked) ? this.generoHombreRef.current.value :
                (this.generoMujerRef.current.checked) ? this.generoMujerRef.current.value :
                    (this.generoOtroRef.current.checked) ? this.generoOtroRef.current.value : '')
        }

        console.log('Formulaio enviado');
        console.log(this.nombreRef.current.value);
        console.log(this.apellidoRef.current.value);
        console.log(this.biografiaRef.current.value);
        console.log(user.genero);

    }

    render() {
        return (
            <React.Fragment>
                <div className="center">
                    <div id="content">
                        <h1 className="subheader">Formulario</h1>
                        <form className="mid-form" onSubmit={this.recibirFormulario}>
                            <div className="form-group">
                                <label htmlFor="name">Nombre</label>
                                <input type="text" name="name" id="" ref={this.nombreRef} />
                            </div>

                            <div className="form-group">
                                <label htmlFor="apellido">Apellidos</label>
                                <input type="text" name="apellido" ref={this.apellidoRef} id="" />
                            </div>

                            <div className="form-group">
                                <label htmlFor="bio">Biografia</label>
                                <textarea name="bio" ref={this.biografiaRef} id=""></textarea>
                            </div>

                            <div className="form-group radiobuttons">
                                <input type="radio" name="genero" ref={this.generoHombreRef} id="" value="Hombre" />Hombre
                                <input type="radio" name="genero" ref={this.generoMujerRef} id="" value="Mujer" />Mujer
                                <input type="radio" name="genero" ref={this.generoOtroRef} id="" value="Otro" />Otro
                            </div>

                            <div className="clearfix"></div>

                            <input type="submit" value="Enviar" className="btn btn-success" />
                        </form>
                    </div>
                </div>
                <Sidebar />
            </React.Fragment>
        );
    }
}

export default Formulario;

// aprendiendo-angular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {
  public user: any;
  public campo: string;

  constructor() {
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    }
  }

  ngOnInit() {
  }

  onSubmit() {
    console.log(this.user);

  }

  hasDadoClick() {
    alert('Has dado click');
  }

  hasSalido(){
    alert('Has dado enter');
  }

}

<app-slider [nombre]="'Formulario'" [size]="'small'">
</app-slider>
<div class="center">
    <section id="content">
        <h1 class="subheader">Formulario</h1>
        <form class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="name">Nombre</label>
                <input type="text" name="name" id="" pattern="[a-zA-Z]" required #nombre="ngModel"
                    [(ngModel)]="user.nombre">
                <small *ngIf="!nombre.valid && nombre.touched">
                    El nombre no es valido
                </small>
            </div>

            <div class="form-group">
                <label for="apellido">Apellidos</label>
                <input type="text" name="apellido" pattern="[a-zA-Z]" id="" required #apellidos="ngModel"
                    [(ngModel)]="user.apellidos">
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Los apellidos no son validos
                </small>
            </div>

            <div class="form-group">
                <label for="bio">Biografia</label>
                <textarea name="bio" id="" #bio="ngModel" required [(ngModel)]="user.bio"></textarea>
                <small *ngIf="!bio.valid && bio.touched">
                    La biografia es requerida
                </small>
            </div>

            <div class="form-group radiobuttons">
                <input type="radio" name="genero" #genero="ngModel" id="" required value="Hombre"
                    [(ngModel)]="user.genero"> Hombre
                <input type="radio" name="genero" #genero="ngModel" id="" value="Mujer" [(ngModel)]="user.genero"> Mujer
                <input type="radio" name="genero" #genero="ngModel" id="" value="Otro" [(ngModel)]="user.genero"> Otro
                <small *ngIf="!apellidos.valid && apellidos.touched">
                    Es obligatorio seleccionar una opcion
                </small>
            </div>

            <div class="clearfix"></div>

            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">
        </form>
        <h2 class="subheader">
            Eventos
        </h2>
        <button (click)="hasDadoClick()">Dale click</button>
        <input type="text" [(ngModel)]="campo" (blur)="hasSalido()">
        <input type="text" [(ngModel)]="campo" (keyup)="hasSalido()">
        {{campo}}

    </section>
    <app-sidebar></app-sidebar>
</div>
