// aprendiendo-react/src/App.js
import React from 'react';
import logo from './assets/images/logo.svg';
import './assets/css/App.css';
import MiComponente from "./componets/MiComponente";
import Peliculas from "./componets/Peliculas";
import Header from "./componets/Header";
import Slider from "./componets/Slider";
import Sidebar from "./componets/Sidebar";
import Footer from "./componets/Footer";

function App() {
  return (
    <div className="App">
      <Header />
      <Slider />
      <div className="center">
        <section id="content">
        </section>
        <Sidebar />
      </div>
      <div class="clearfix"></div>
      <Footer />
    </div>
  );
}

export default App;

// aprendiendo-vue/src/App.vue
<template>
  <div id="app">
    <Header />
    <slider />
    <div class="center">
      <section class="content">
        <last-articles />
        <Sidebar />
      </section>
    </div>
    <div class="clearfix"></div>
    <Footer />
  </div>
</template>

<script>
import Header from "./components/Header.vue";
import Slider from "./components/Slider.vue";
import Sidebar from "./components/Sidebar.vue";
import LastArticles from "./components/LastArticles.vue";
import Footer from "./components/Footer.vue";

export default {
  name: "App",
  components: {
    Header,
    Slider,
    Sidebar,
    LastArticles,
    Footer
  }
};
</script>

<style>
@import "./assets/css/styles.css";
</style>
