// aprendiendo-react/src/componets/Article.js
import React, { Component } from "react";
import axios from 'axios';
import Global from '../Global'
import Moment from "react-moment";
import 'moment/locale/es';
import Sidebar from "./Sidebar";
import Helpers from "./Helpers";
import { Link, Redirect } from "react-router-dom";
import swal from 'sweetalert';

class Article extends Component {

    url = Global.url;
    helper = Helpers;
    state = {
        article: null,
        status: null,
        eliminado: false
    }

    componentWillMount = () => this.getArticle();

    getArticle = () => {
        var id = this.props.match.params.id;

        axios.get(this.url + 'article/' + id).then(
            res => {
                this.setState(
                    {
                        article: res.data.article,
                        status: 'success'
                    }
                );
            }
        ).catch(err => {
            this.setState(
                {
                    article: null,
                    status: 'failed'
                }
            );
        });
    }

    deleteArticle = (id, title) => {
        swal("¿Esta seguro que desea eliminar este articulo?", {
            dangerMode: true,
            buttons: true,
        }).then(res => {
            if (res)
                axios.delete(this.url + 'article/' + id).then(
                    res => {
                        if (res.data.article) {
                            this.setState(
                                {
                                    article: res.data.article,
                                    status: 'success',
                                    eliminado: true
                                }
                            );
                            swal('Exito',
                                'Se ha eliminado correctamente',
                                'success');
                        }
                    }
                ).catch(err => {
                    console.log(err);
                    swal('Error',
                        'Lo siento, hubo un error al intentar eliminar el articulo, contacte al administrador',
                        'error');
                });

        });
    }

    render() {
        if (this.state.eliminado)
            return <Redirect to="/blog"></Redirect>
        var article = this.state.article;
        return (
            <div className="center">
                <section id="content">
                    {article &&
                        <article className="article-item article-detail">
                            <div className="image-wrap">
                                {<img src={this.helper.obtenerImagen(article.image || null)} alt={article.title} />}
                            </div>

                            <h1 className="subheader">{article.title}</h1>
                            <span className="date">
                                <Moment locale="es" fromNow >{article.date}</Moment>
                            </span>
                            <p>
                                {article.content}
                            </p>
                            <button
                                onClick={
                                    () => {
                                        this.deleteArticle(article._id, article.title)
                                    }
                                }
                                className="btn btn-danger">Eliminar</button>
                            <Link className="btn btn-warning" to={"/blog/articulo/editar/" + article._id}>Editar</Link>
                            <div className="clearfix"></div>
                        </article>
                    }
                    {this.state.status === 'failed' &&
                        <div id="article">
                            <h2 className="subheader">El articulo no existe</h2>
                            <p>Por favor intentelo de nuevo mas tarde</p>
                        </div>
                    }


                    {this.state.status == null &&
                        <div id="article">
                            <h2 className="subheader">Cargando</h2>
                            <p> Por favor espere unos segundos</p>
                        </div>

                    }
                </section>
                <Sidebar />
            </div >
        );
    }
}

export default Article;

// aprendiendo-angular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { Route, ActivatedRoute, Params, Router } from '@angular/router';
import { global } from '../../services/global';
import swal from 'sweetalert';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public url: string;

  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = global.url;
  }

  ngOnInit() {
    this._route.params.subscribe(params => {
      let id = params['id'];
      this._articleService.getArticle(id).subscribe(
        response => {
          if (response.article) {
            this.article = response.article;
          } else {
            this._router.navigate(['/home']);
          }
        },
        err => {
          this._router.navigate(['/home']);
        }
      )
    });
  }

  delete(id) {
    swal({
      title: "Estas seguro?",
      text: "Una ves borrado el articulo no podras recuperarlo",
      icon: "warning",
      buttons: [true,true],
      dangerMode: true
    })
      .then((willDelete) => {
        if (willDelete) {
          this._articleService.delete(id).subscribe(
            response => {
              swal("Articulo eliminado correctamente", {
                icon: "success",
              });
              this._router.navigate(['/blog']);
            },
            error => {
              console.log(error);
              this._router.navigate(['/blog']);
            }
          );
        } else {
          swal("Se ha cancelado la eliminacion.");
        }
      });
  }

}

<app-slider [nombre]="'Articulo'" [size]="'small'">
</app-slider>
<div class="center">
    <section id="content">
        <article class="article-item article-detail" *ngIf="article">
            <div class="image-wrap">
                <img src="{{url + 'get-image/'+article.image}}" alt="{{article.title}}">
            </div>

            <h1 class="subheader">{{article.title}}</h1>
            <span class="date">
                {{article.date | amLocale: 'es' | amTimeAgo}}
            </span>
            <p>{{article.content}}</p>
            <div class="buttons">
                <a class="btn btn-warning" [routerLink]="['/blog/editar/', article._id]">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
            </div>
            <div class="clearfix"></div>
        </article>
    </section>
    <app-sidebar></app-sidebar>
</div>
