// aprendiendo-react/src/componets/Header.js
import React, { Component } from "react";
import logo from "../assets/images/logo.svg";

class Header extends Component {
    render() {
        return (
            <header id="header">
                <div className="center">

                    <div id="logo">
                        <img src={logo} alt="Logotipo" className="app-logo" />
                        <span id="brand">
                            <strong>Curso</strong> React
                    </span>
                    </div>

                    {/*comentario*/}
                    <nav id="menu">
                        <ul>
                            <li><a href="index.html">Inicio</a></li>
                            <li><a href="blog.html">Blog</a></li>
                            <li><a href="formulario.html">Formulario</a></li>
                            <li><a href="#">Pagina 1</a></li>
                            <li><a href="#">Pagina 2</a></li>
                        </ul>
                    </nav>
                    <div className="clearfix"></div>
                </div>
            </header>
        );
    }
}

export default Header;

// aprendiendo-vue/src/components/Header.vue
<template>
  <header id="header">
    <div class="center">
      <!-- Logo -->
      <div id="logo">
        <img src="../assets/logo.png" alt="Logotipo" class="app-logo" />
        <span id="brand">
          <strong>Curso</strong> Vue
        </span>
      </div>

      <!-- Menu -->
      <nav id="menu">
        <ul>
          <li>
            <a href="index.html">Inicio</a>
          </li>
          <li>
            <a href="blog.html">Blog</a>
          </li>
          <li>
            <a href="formulario.html">Formulario</a>
          </li>
          <li>
            <a href="#">Pagina 1</a>
          </li>
          <li>
            <a href="#">Pagina 2</a>
          </li>
        </ul>
      </nav>

      <!-- Limpiar flotados -->
      <div class="clearfix"></div>
    </div>
  </header>
</template>
<script>
export default {
  name: "Header"
};
</script>
