// aprendiendo-angular/src/app/components/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';

@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {
  @Input() pelicula: Pelicula;
  @Output() MarcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit() {
  }

  seleccionar(event, pelicula) {
    this.MarcarFavorita.emit({
      pelicula: pelicula
    });
  }

}

<div id="articles">
    <article class="article-item" id="article-template">
        <div class="image-wrap">
            <img src="{{pelicula.image}}" alt="{{pelicula.title}}">
        </div>

        <h2>{{pelicula.title}}</h2>
        <span class="date">
            Hace 5 minutos
        </span>
        <span [ngClass]="{
        'year-green': pelicula.year > 2019,
        'year-red': pelicula.year < 2020
    }">
            {{pelicula.year}}
        </span>
        <a href="#">Leer mas</a>
        <button (click)="seleccionar($event, pelicula)">Seleccionar como favorita</button>
        <div class="clearfix"></div>
    </article>
    <!-- Añadir articulos via js -->
</div>

// aprendiendo-vue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" />
    </div>

    <h2>{{pelicula.title}}</h2>
    <span
      class="date"
      :class="{
            yeargreen: pelicula.year >=2016,
            yearred: pelicula.year <2016
        }"
    >{{pelicula.year}}</span>
    <button @click="marcarFavorita(pelicula)">Marcar como Favorita</button>
    <div class="clearfix"></div>
  </article>
</template>
<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    marcarFavorita(pelicula) {
      console.log(pelicula.title);
      this.$emit("favorita", pelicula);
    }
  }
};
</script>
