// aprendiendo-angular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css'],

})
export class SidebarComponent implements OnInit {

  public searchString: string;

  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ) { }

  ngOnInit() {
  }

  goSearch() {
    this._router.navigate(['/buscar', this.searchString]);
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="" class="btn btn-success">Crear articulo</a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el articulo que buscas</p>
        <form action="" #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" id="" #search [(ngModel)]="searchString">
            <input type="submit" class="btn" value="Buscar">
        </form>
    </div>
</aside>
<div class="clearfix"></div>

// aprendiendo-vue/src/components/Sidebar.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href class="btn btn-success">Crear articulo</a>
    </div>

    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el articulo que buscas</p>
      <form action>
        <input type="text" name="search" id />
        <input type="submit" class="btn" value="Buscar" />
      </form>
    </div>
  </aside>
</template>
<script>
export default {
  name: "Sidebar"
};
</script>
