// aprendiendo-vue/src/components/Blog.vue
<template>
  <div class="general">
    <slider texto="Blog" />
    <div class="center">
      <section id="content">
        <h2 class="subheader">Blog</h2>
      </section>
      <sidebar />
    </div>
  </div>
</template>
<script>
import Slider from "./Slider.vue";
import Sidebar from "./Sidebar.vue";

export default {
  name: "Blog",
  components: {
    Slider,
    Sidebar
  }
};
</script>

// aprendiendo-react/src/componets/Blog.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Blog extends Component {
    render() {
        return (
            <React.Fragment>
                <Slider tittle="Blog" />
                <div className="center">
                    <div id="content">
                        {/* Listado de articulos que vendran del api */}
                    </div>
                </div>
                <Sidebar blog="true" />
            </React.Fragment>
        );
    }
}

export default Blog;
