// aprendiendo-angular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  public title: string;

  constructor() { 
    this.title = 'Ultimos articulos'
  }

  ngOnInit() {
  }

}

<app-slider [nombre]="'Bienvenido al blog de Selvin'">
</app-slider>
<div class="center">
    <section id="content">
        <h2 class="subheader">{{title}}</h2>
        <app-articles [articles]="articles"></app-articles>
    </section>
    <app-sidebar></app-sidebar>
</div>

// aprendiendo-react/src/componets/Home.js
import React, { Component } from "react";
import Slider from "./Slider";
import Sidebar from "./Sidebar";

class Home extends Component {
    render() {
        return (
            <React.Fragment>
                <Slider tittle="Bienvenido al curso de React de Selvin Medina" buttonString={"Ir al blog"} />
                <div className="center">
                    <div id="content">
                        <h1 className="subheader">Últimos articulos</h1>
                    </div>
                </div>
                <Sidebar />
            </React.Fragment>
        );
    }
}

export default Home;
