// aprendiendo-vue/src/components/Pelicula.vue
<template>
  <article class="article-item">
    <div class="image-wrap">
      <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" />
    </div>

    <h2>{{pelicula.title}}</h2>
    <span
      class="date"
      :class="{
            yeargreen: pelicula.year >=2016,
            yearred: pelicula.year <2016
        }"
    >{{pelicula.year}}</span>
    <button @click="marcarFavorita(pelicula)">Marcar como Favorita</button>
    <div class="clearfix"></div>
  </article>
</template>
<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    marcarFavorita(pelicula) {
      console.log(pelicula.title);
      this.$emit("favorita", pelicula);
    }
  }
};
</script>

// aprendiendo-react/src/componets/Pelicula.js
import React, { Component } from "react";

class Pelicula extends Component {
  marcar(){
    this.props.marcarFavorita(this.props.pelicula);
  }

  render() {
    const pelicula = this.props.pelicula;
    const { titulo, image } = this.props.pelicula;

    return (
      <article className="article-item article-detail">
        <div className="image-wrap">
          <img src={image} alt={titulo} />
        </div>

        <h1 className="subheader">{titulo}</h1>
        <span className="date">Hace 5 minutos</span>
        <button onClick={this.marcar}>
        Marcar como favorita 
        </button>
        <div className="clearfix"></div>
      </article>
    );
  }
}

export default Pelicula;
